matrix:
  include:
    - os: osx
      env: ACTION=lint
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=OSX
    - os: osx
      env: ACTION=tvOS

language: objective-c
osx_image: xcode8

script:
  - make install-$ACTION && make test-$ACTION
